spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cloudriverdale_springBoot
    username: ${DB_USERNAME:postgres}  # 환경변수가 없으면 postgres 사용
    password: ${DB_PASSWORD:password}   # 환경변수가 없으면 password 사용
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update  # 테이블 자동 생성/업데이트
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true  # SQL 보기 좋게 포맷팅
    show-sql: true  # 콘솔에 SQL 출력

jwt:
  secret: ${JWT_SECRET:mySecretKey12345678901234567890}
  expiration: 3600000  # 1시간 (밀리초)

server:
  port: 8080
