spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cloudriverdale_springBoot_dev
    username: devuser
    password: devpass
  
  jpa:
    hibernate:
      ddl-auto: create-drop  # 앱 시작시 테이블 생성, 종료시 삭제
    show-sql: true

server:
  port: 8081
